{% set version = "0.0.8" %}

package:
  name: safety-schemas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety-schemas/safety_schemas-{{ version }}.tar.gz
  sha256: f4c63b7012facc2f59b9abcbe48acfd5bd5068e58e62d39753db4667499320fa

build:
  noarch: python
  script:
    - {{ PYTHON }} -c "from pathlib import Path; [p.unlink() for p in Path.cwd().rglob('.DS_Store')]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - dparse >=0.6.4b0
    - ruamel.yaml >=0.17.21
    - packaging >=21.0
    - pydantic >=2.5.0,<2.6
    - python >=3.7.0
    - typing-extensions >=4.7.1

test:
  imports:
    - safety_schemas
    - safety_schemas.models
    - safety_schemas.report
    - safety_schemas.config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/safety-schemas
  summary: Schemas for Safety CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
